name: Triggered Deploy to AWS

on:
  push:
    branches:
      - development
      - staging
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # true OR recursive
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Set bucket for branch
        id: deploy-bucket
        run: |
          if [[ $GITHUB_REF == 'refs/heads/development' ]]; then
              echo "::set-output name=TOOL_BUCKET::eviction-lab-dev"
              echo "::set-output name=MAP_BUCKET::eviction-lab-dev"
              echo "::set-output name=RANKINGS_BUCKET::eviction-lab-dev"
              echo "::set-output name=CLOUDFRONT_ID::${{ secrets.CLOUDFRONT_ID_DEV }}"
          elif [[ $GITHUB_REF == 'refs/heads/staging' ]]; then
              echo "::set-output name=TOOL_BUCKET::eviction-lab-tool-staging"
              echo "::set-output name=MAP_BUCKET::eviction-lab-map-staging"
              echo "::set-output name=RANKINGS_BUCKET::eviction-lab-rankings-staging"
              echo "::set-output name=CLOUDFRONT_ID::${{ secrets.CLOUDFRONT_ID_STAGING }}"
          elif [[ $GITHUB_REF == 'refs/heads/production' ]]; then
              echo "::set-output name=TOOL_BUCKET::eviction-lab-tool"
              echo "::set-output name=MAP_BUCKET::eviction-lab-map"
              echo "::set-output name=RANKINGS_BUCKET::eviction-lab-rankings"
              echo "::set-output name=CLOUDFRONT_ID::${{ secrets.CLOUDFRONT_ID_PROD }}"
          fi

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: NPM install
        run: npm ci

      - name: Setup Angular
        run: |
          npm install -g @angular/cli@v12
          ng lint

      - name: Build
        run: |
          if [[ $GITHUB_REF == 'refs/heads/development' ]]; then
            npm run build-dev
          elif [[ $GITHUB_REF == 'refs/heads/staging' ]]; then
            npm run build-staging
          elif [[ $GITHUB_REF == 'refs/heads/production' ]]; then
            npm run build-prod
          fi

      - name: Before deploy
        run: |
          pip install --user awscli
          export PATH=$PATH:$HOME/.local/bin

      - name: Deploy
        run: |
          aws s3 cp dist/ s3://${{ steps.deploy-bucket.outputs.TOOL_BUCKET }}/tool --acl=public-read --recursive --cache-control max-age=604800
          aws s3 cp dist/index.html s3://${{ steps.deploy-bucket.outputs.MAP_BUCKET }}/map/index.html --acl=public-read --cache-control max-age=3600

          node ./build/update-metadata.js
          aws s3 cp dist/index.html s3://${{ steps.deploy-bucket.outputs.RANKINGS_BUCKET }}/rankings/index.html --acl=public-read --cache-control max-age=3600

          aws cloudfront create-invalidation --distribution-id=${{ steps.deploy-bucket.outputs.CLOUDFRONT_ID }} --paths="/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
